---
site_name: Linux Training @HOGENT
site_url: https://hogenttin.github.io/linux-training-hogent/
repo_name: "HoGentTIN/linux-training-hogent"
repo_url: "https://github.com/HoGentTIN/linux-training-hogent"
edit_uri: "edit/main/docs/"

nav:
  - 'Home': index.md
  - 'Introduction': 
      - 'Linux History': introduction-to-linux/linux-history.md
      - 'Licensing': introduction-to-linux/licensing.md
      - 'Linux Distributions': introduction-to-linux/linux-distributions.md
      - 'Installing CentOS 7': introduction-to-linux/installing-centos7.md
      - 'Installing Debian 8': introduction-to-linux/installing-debian8.md
      - 'Getting Linux at home': introduction-to-linux/virtualbox.md
  - 'First steps':
      - 'Man pages': first-steps/man-pages.md
      - 'Working with directories': first-steps/working-with-directories.md
      - 'Working with files': first-steps/working-with-files.md
      - 'Working with file contents': first-steps/working-with-file-contents.md
      - 'File system tree': first-steps/file-system-tree.md

not_in_nav: |
  /index.md