---
name: publish 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.19'
      - name: Install Python libraries
        run: pip install mkdocs mkdocs-material pymdown-extensions shyaml
      - name: Run publish script
        run: bash ./lib/publish.sh
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the gh-pages directory
          path: 'gh-pages/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4